project:
  type: book
  output-dir: _book

book:
  title: "Mastering Nextflow: From Fundamentals to Expert Practice"
  author: "Shaojun Xie"
  chapters:
  - index.qmd
  - preface.qmd
  - introduction.qmd

  - part: Analysis of WGBS data
    chapters:
      - nf_wgb_analysis.qmd

  - part: Getting Started with Nextflow
    chapters:
      - nf_installation.qmd
      - nf_your_first_pipeline.qmd

  - part: Running Nextflow workflows
    chapters:
      - nf_configuration.qmd

  - part: Foundations
    chapters: 
      - nf_workflow_overview.qmd
      - nf_channels_processes.qmd
      - nf_DSL2.qmd
      - nf_workflow.qmd

  - part: Building Real Pipelines
    chapters:
      - nf_results.qmd

  - part: Advanced Topics
    chapters:
      - nf_advanced_metadata.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  # pdf:
  #   toc: true
  #   number-sections: true
    #include-in-header: preamble.tex
    

publish:
  on: gh-pages
